[package]
name = "esphome-native-api"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
tokio = { version = "1", features = ["full"] }
prost = "0.13.5"

[build-dependencies]
prost-build = "0.13"